// <auto-generated />
namespace FirstTask_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RecruitRequest_Skill_SkillId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecruitRequest_Skill_SkillId));
        
        string IMigrationMetadata.Id
        {
            get { return "202101240353136_RecruitRequest_Skill_SkillId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
